name: Docs
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install Python
      uses: actions/setup-python@v1

    - name: Install 
      run: pip install -e .[dev]
      
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
